apiVersion: v2
name: invidious
description: Invidious is an alternative front-end to YouTube
version: 1.0.0
appVersion: 0.20.1
keywords:
- youtube
- proxy
- video
- privacy
home: https://invidio.us/
sources:
- https://github.com/omarroth/invidious
maintainers:
- name: Leon Klingele
  email: mail@leonklingele.de
dependencies:
- name: postgresql
  version: ~8.3.0
  repository: "https://kubernetes-charts.storage.googleapis.com/"
engine: gotpl
